ALTER TABLE public.ausencias
ADD COLUMN IF NOT EXISTS hora_inicio TIME WITHOUT TIME ZONE,
ADD COLUMN IF NOT EXISTS hora_fim TIME WITHOUT TIME ZONE,
ADD COLUMN IF NOT EXISTS recorrencia TEXT DEFAULT 'nenhuma',
ADD COLUMN IF NOT EXISTS dias_semana JSONB,
ADD COLUMN IF NOT EXISTS dia_mes INTEGER,
ADD COLUMN IF NOT EXISTS data_fim DATE;
